logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
   name: grupo8-oo2
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    #properties:
      #dialect: org.hibernate.dialect.MySQL5Dialect
  
   